#!/usr/bin/env python3
r"""Make the captions available to the pages that place photographs by hand.

Reads assets/data/captions.toml and writes assets/data/captions.tex, a run of
\photocaptiondef -- one per photograph, filed under the name
\includegraphics is given for it. main.tex inputs that file, and \mountedphoto
looks a caption up by the plate it was handed:

    \mountedphoto{plates/plate-desk}

so a section says which photograph goes where and the caption file says what
it is called. Nothing in sections/ carries caption text, which is the point:
the words live in one file the family can edit, and they are the same words
wherever that photograph is printed.

The two generated sections -- the family album and the tributes -- do not go
through this file. They read captions.py directly, because both have to know
a caption is there before they can lay the page out: the album reserves the
depth a caption takes when it solves its rows, and a tribute's photograph
sits in a column the letter flows around. This file is for the pages a
person composed.

Edit the TOML and re-run assets/make-plates.sh (or this script on its own;
latexmk also runs it when the TOML is the newer of the two).
"""

import pathlib
import re
import sys

import captions as captionfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
TEX = ROOT / "assets/data/captions.tex"

# Characters that cannot appear in a key, because the key is written into a
# .tex file and then built into a control sequence name with \csname:
#
#   \ { }   would be read as LaTeX rather than as part of the name
#   %       would comment out the rest of the generated line
#   #       is a parameter character, and ends the argument early
#   ~       is active, and \csname expands what it scans, so it would come
#           out as \nobreakspace rather than as a tilde
#
# Everything else a filename is likely to hold -- spaces, dots, hyphens,
# slashes, ampersands -- is an ordinary character to \csname and comes
# through as itself.
UNSAFE = re.compile(r"[\\{}%#~]|[^\x20-\x7e]")


def main():
    captions = captionfile.load()

    for key in captions.missing:
        print(f"build-captions: {key} -- no such image", file=sys.stderr)
    for key in captions.unresolved():
        print(f"build-captions: {key} is outside assets/images/, so nothing "
              "can print it", file=sys.stderr)

    lines = ["% Generated by assets/build-captions.py -- do not edit by hand.",
             "% Edit assets/data/captions.toml and re-run "
             "assets/make-plates.sh.",
             "%",
             "% One definition per captioned photograph, filed under the name",
             r"% \includegraphics is given for it. \mountedphoto looks its "
             "caption up",
             "% here; a photograph with no line below is printed without one.",
             ""]

    written = 0
    for image, text in captions.items():
        name = captionfile.graphics_key(image)
        if name is None:
            continue          # already reported by unresolved(), above
        if UNSAFE.search(name):
            print(f"build-captions: {image} cannot be named to LaTeX -- its "
                  "path holds a character that cannot go in a control "
                  "sequence", file=sys.stderr)
            continue
        lines.append(r"\photocaptiondef{%s}{%s}" % (name, text))
        written += 1

    TEX.write_text("\n".join(lines) + "\n")
    print(f"build-captions: {written} caption{'' if written == 1 else 's'} "
          f"-> {TEX.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
